### ISSUE TITLE
是否考虑将php的ssl验证去掉或者是加一个配置项呢

### ISSUE THREAD

**Issue by fly2006zhao** [wowiwj/ding-notice#1]

**Comment by wowiwj** [comment]
为什么要去掉呢，不去掉的话对你使用有什么影响？

**Comment by fly2006zhao** [comment]
@wowiwj 默认大家的环境里面，都没有安装相关的证书文件到php，这样的话GuzzleHttp底层会报一个ssl验证失败的错误，所以能否增加一下这个配置兼容一下 
像这样
![image](https://user-images.githubusercontent.com/5717074/57910624-5496df00-78b8-11e9-9e26-54a81a320759.png)

**Comment by wowiwj** [comment]
我觉得可以哈，你提交个PR或者我回去了加一下

**Comment by fly2006zhao** [comment]
@wowiwj 已经提交pr

**Comment by wowiwj** [comment]
@fly2006zhao 已合并

**Comment by fly2006zhao** [comment]
@wowiwj 是否考虑加一下新的版本号呢

**Comment by wowiwj** [comment]
@fly2006zhao 已添加哦
