### ISSUE TITLE
安全设置-加签 不支持么？

### ISSUE THREAD

**Issue by meng458544582341** [wowiwj/ding-notice#11]
安全设置-加签 不支持么？

**Comment by hongweipeng** [comment]
同问

**Comment by wowiwj** [comment]
@meng458544582341  @hongweipeng   支持的，具体在配置文件里面有配置 https://github.com/wowiwj/ding-notice/blob/1cb690dbaf71d82f6e11c8a96c2bbd63c1dc01d8/config/ding.php#L17

**Comment by meng458544582341** [comment]
@wowiwj 
{
  "errcode":310000,
   "errmsg":"sign not match"
}
返回签名不匹配，这个怎么破呢？

**Comment by wowiwj** [comment]
@meng458544582341 https://github.com/wowiwj/ding-notice/pull/12 ,已修复，更新最新版本即可

**Comment by meng458544582341** [comment]
@wowiwj  OK了。为啥去掉urlencode就可以了呢？

> 文档中描述需要urlEncode的：把timestamp+"\n"+密钥当做签名字符串，使用HmacSHA256算法计算签名，然后进行Base64 encode，最后再把签名参数再进行urlEncode，得到最终的签名（需要使用UTF-8字符集）。

**Comment by wowiwj** [comment]
@meng458544582341 https://www.php.net/manual/zh/function.http-build-query.php 这个函数自带 urlEncode
