### ISSUE TITLE
钉钉新增[安全设置]

### ISSUE THREAD

**Issue by okami-chen** [wowiwj/ding-notice#5]
https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq 增加签名？

**Comment by wowiwj** [comment]
https://github.com/okami-chen/ding-notice/blob/1c6e279472add2b4b806d6638ef324028561cbe5/src/HttpClient.php#L72

可以把加密参数也放到getRobotUrl里面，同时配置文件也应该更新一下:) ,感觉放到send不太好
